/**
 * API keys — machine-principal issuance & authentication decisions (issue #46,
 * SPEC §34 "Never store plaintext passwords" applied to machine credentials).
 *
 * Model:
 *   - issuance record: visible `prefix` (first KEY_PREFIX_LENGTH chars of the
 *     secret), the secret HASH via the INJECTED SecretCodec port (the domain
 *     never imports a crypto library — it owns decisions, the adapter owns
 *     cryptography), concrete-permission `scopes` (a subset of the closed
 *     role vocabulary — wildcards are forbidden per grant/scope), optional
 *     expiry, `lastUsedAt` tracked via the injected clock;
 *   - revocation is a FACT (`status: 'revoked'` + revokedBy/reason) — replay
 *     of a revoked key returns a denial + audit event forever after;
 *   - `authenticateKey` is a DECISION VALUE path: every denial (unknown
 *     prefix, hash mismatch, revoked, expired, owner suspended) carries a
 *     stable KEY_* code AND the `auth.accessDenied` audit event — denials are
 *     first-class facts, never exceptions. Only a broken codec throws.
 *
 * Denial precedence (deterministic, tests pin it):
 *   KEY_UNKNOWN → KEY_SECRET_MISMATCH → KEY_REVOKED → KEY_EXPIRED →
 *   KEY_OWNER_INACTIVE. A revoked key denies even when the secret matches;
 *   an expired one denies before ownership is consulted.
 */
import { DomainError, type Clock, type Uuid } from '../shared';
import { assertPermission, type Permission } from './roles';
import {
  authEvent,
  type AccessDeniedPayload,
  type ApiKeyIssuedPayload,
  type ApiKeyRevokedPayload,
  type AuthEvent,
  type DenyReason,
} from './events';
import {
  assertClockDate,
  assertNonBlank,
  assertSecretCodec,
  type SecretCodec,
  type UserStatus,
} from './user';

/** Visible prefix length — enough to pick a key row, useless for auth. */
export const KEY_PREFIX_LENGTH = 8;

/** Minimum length of the raw API-key secret (machine secrets run longer). */
export const KEY_SECRET_MIN_LENGTH = 16;

/** The KEY_* slice of DenyReason — the codes authenticateKey can return. */
export type KeyDenyReason =
  | 'KEY_UNKNOWN'
  | 'KEY_SECRET_MISMATCH'
  | 'KEY_REVOKED'
  | 'KEY_EXPIRED'
  | 'KEY_OWNER_INACTIVE';

export type ApiKeyStatus = 'active' | 'revoked';

export interface ApiKey {
  readonly keyId: Uuid;
  readonly orgId: Uuid;
  readonly name: string;
  /** The user (opaque id) that issued the key — the suspension cascade hook. */
  readonly createdBy: Uuid;
  /** Visible identifier — the first KEY_PREFIX_LENGTH chars of the secret. */
  readonly prefix: string;
  /** Codec output — the raw secret is never stored anywhere. */
  readonly secretHash: string;
  /** Concrete vocabulary subset, deduped + sorted (never a wildcard). */
  readonly scopes: readonly Permission[];
  readonly expiresAt: Date | null;
  readonly status: ApiKeyStatus;
  readonly createdAt: Date;
  readonly lastUsedAt: Date | null;
  readonly revokedAt: Date | null;
  readonly revokedBy: Uuid | null;
  readonly revokedReason: string | null;
}

// --- issuance -----------------------------------------------------------------------

export interface IssueKeyArgs {
  readonly keyId: Uuid;
  readonly orgId: Uuid;
  readonly name: string;
  readonly createdBy: Uuid;
  /** Raw secret — generated by the ADAPTER (no RNG in the domain); hashed immediately. */
  readonly secret: string;
  readonly scopes: readonly string[];
  readonly expiresAt?: Date | null;
}

/**
 * Issue an API key: hash via the injected port, keep the prefix visible,
 * emit `auth.apiKeyIssued` (payload carries the prefix and scopes — never
 * the secret, never the hash).
 *
 * Throws:
 *   - AUTH_KEY_ID_TAKEN / AUTH_KEY_NAME_REQUIRED;
 *   - AUTH_KEY_PREFIX_TAKEN — prefix collision (two secrets sharing a prefix
 *     would make prefix lookup ambiguous; the adapter generates a fresh one);
 *   - AUTH_KEY_SCOPES_REQUIRED — empty scope list (a key that can do nothing
 *     is a confusion, not a key);
 *   - AUTH_PERMISSION_* — wildcard/malformed/unknown scope (assertPermission:
 *     scopes are CONCRETE permissions only);
 *   - AUTH_SECRET_TOO_SHORT (KEY_SECRET_MIN_LENGTH) / AUTH_HASH_PORT_INVALID;
 *   - AUTH_KEY_EXPIRY_INVALID — expiry not strictly after issuance;
 *   - AUTH_CLOCK_INVALID.
 */
export function issueKey(
  existingKeys: readonly ApiKey[],
  args: IssueKeyArgs,
  codec: SecretCodec,
  clock: Clock,
): { key: ApiKey; event: AuthEvent<'auth.apiKeyIssued', ApiKeyIssuedPayload> } {
  if (existingKeys.some((k) => k.keyId === args.keyId)) {
    throw new DomainError('AUTH_KEY_ID_TAKEN', `api key ${args.keyId} already exists`, {
      keyId: args.keyId,
    });
  }
  const name = assertNonBlank(args.name, 'AUTH_KEY_NAME_REQUIRED', 'key name');
  assertNonBlank(args.createdBy, 'AUTH_ACTOR_REQUIRED', 'issuer id');

  if (args.scopes.length === 0) {
    throw new DomainError(
      'AUTH_KEY_SCOPES_REQUIRED',
      'an api key must carry at least one concrete scope',
    );
  }
  const scopes = [...new Set(args.scopes.map(assertPermission))].sort();

  assertSecretCodec(codec);
  if (typeof args.secret !== 'string' || args.secret.length < KEY_SECRET_MIN_LENGTH) {
    throw new DomainError(
      'AUTH_SECRET_TOO_SHORT',
      `an api-key secret requires at least ${KEY_SECRET_MIN_LENGTH} characters`,
    );
  }
  const prefix = args.secret.slice(0, KEY_PREFIX_LENGTH);
  if (existingKeys.some((k) => k.prefix === prefix)) {
    throw new DomainError(
      'AUTH_KEY_PREFIX_TAKEN',
      `api-key prefix '${prefix}' is already in use — generate a fresh secret`,
      { prefix },
    );
  }

  const createdAt = assertClockDate(clock.now(), 'AUTH_CLOCK_INVALID');
  let expiresAt: Date | null = null;
  if (args.expiresAt !== undefined && args.expiresAt !== null) {
    const at = assertClockDate(args.expiresAt, 'AUTH_KEY_EXPIRY_INVALID');
    if (at.getTime() <= createdAt.getTime()) {
      throw new DomainError(
        'AUTH_KEY_EXPIRY_INVALID',
        'an api key must expire strictly after its issuance instant',
      );
    }
    expiresAt = at;
  }

  const key: ApiKey = {
    keyId: args.keyId,
    orgId: args.orgId,
    name,
    createdBy: args.createdBy,
    prefix,
    secretHash: codec.hash(args.secret),
    scopes,
    expiresAt,
    status: 'active',
    createdAt,
    lastUsedAt: null,
    revokedAt: null,
    revokedBy: null,
    revokedReason: null,
  };
  const payload: ApiKeyIssuedPayload = {
    keyId: key.keyId,
    orgId: key.orgId,
    name: key.name,
    prefix: key.prefix,
    scopes: key.scopes,
    expiresAt: expiresAt === null ? null : expiresAt.toISOString(),
    createdBy: key.createdBy,
    issuedAt: createdAt.toISOString(),
  };
  return { key, event: authEvent('auth.apiKeyIssued', key.keyId, payload, clock) };
}

// --- revocation ------------------------------------------------------------------------

export interface RevokeKeyArgs {
  readonly keyId: Uuid;
  readonly revokedBy: Uuid;
  readonly reason: string;
}

export type RevokeKeyResult =
  | {
      readonly revoked: true;
      readonly key: ApiKey;
      readonly event: AuthEvent<'auth.apiKeyRevoked', ApiKeyRevokedPayload>;
      readonly alreadyRevoked: false;
    }
  | {
      /** Idempotent replay: the key is already revoked; original returned, no event. */
      readonly revoked: true;
      readonly key: ApiKey;
      readonly event: null;
      readonly alreadyRevoked: true;
    };

/**
 * Revoke a key — a FACT on the issuance record. Idempotent: revoking an
 * already-revoked key returns the original record unchanged (adapter retries
 * are safe); revoking an UNKNOWN key is AUTH_KEY_NOT_FOUND.
 */
export function revokeKey(
  existingKeys: readonly ApiKey[],
  args: RevokeKeyArgs,
  clock: Clock,
): RevokeKeyResult {
  const reason = assertNonBlank(args.reason, 'AUTH_REASON_REQUIRED', 'revocation reason');
  assertNonBlank(args.revokedBy, 'AUTH_ACTOR_REQUIRED', 'revoker id');
  const target = existingKeys.find((k) => k.keyId === args.keyId);
  if (!target) {
    throw new DomainError('AUTH_KEY_NOT_FOUND', `api key ${args.keyId} does not exist`, {
      keyId: args.keyId,
    });
  }
  if (target.status === 'revoked') {
    return { revoked: true, key: target, event: null, alreadyRevoked: true };
  }
  const revokedAt = assertClockDate(clock.now(), 'AUTH_CLOCK_INVALID');
  const key: ApiKey = {
    ...target,
    status: 'revoked',
    revokedAt,
    revokedBy: args.revokedBy,
    revokedReason: reason,
  };
  const payload: ApiKeyRevokedPayload = {
    keyId: key.keyId,
    orgId: key.orgId,
    revokedBy: args.revokedBy,
    reason,
    revokedAt: revokedAt.toISOString(),
  };
  return {
    revoked: true,
    key,
    event: authEvent('auth.apiKeyRevoked', key.keyId, payload, clock),
    alreadyRevoked: false,
  };
}

// --- authentication decisions --------------------------------------------------------------

export interface AuthenticateKeyArgs {
  /** Org context of the authentication attempt (denials aggregate on it). */
  readonly orgId: Uuid;
  /** The presented raw secret — prefix picks the row, the codec decides the rest. */
  readonly secret: string;
  /**
   * Status of the key's `createdBy` user, when the adapter has it loaded.
   * The suspension cascade: a suspended owner's key denies even though the
   * key itself is fine. Null/absent = ownership not consulted.
   */
  readonly ownerStatus?: UserStatus | null;
}

export type AuthenticateKeyResult =
  | { readonly authenticated: true; readonly key: ApiKey; readonly event: null }
  | {
      readonly authenticated: false;
      /** Stable KEY_* code — adapters match on this, never on prose. */
      readonly code: KeyDenyReason;
      readonly reason: KeyDenyReason;
      readonly detail: string;
      /** auth.accessDenied — persist next to the denial decision (audit). */
      readonly event: AuthEvent<'auth.accessDenied', AccessDeniedPayload>;
    };

/**
 * The permission marker used in `auth.accessDenied` payloads for
 * authentication attempts themselves (not a vocabulary permission — the
 * attempt is "be authenticated", authorization happens after).
 */
export const AUTH_ATTEMPT_PERMISSION = 'auth:authenticate';

/**
 * Authenticate a presented API key. Pure decision: no I/O, hashing behind
 * the injected codec. Every denial is a VALUE paired with the
 * `auth.accessDenied` audit event (aggregate = the key when known, the org
 * when not); success stamps `lastUsedAt` via the injected clock and emits no
 * event (usage tracking is the audit).
 *
 * Denial precedence: KEY_UNKNOWN → KEY_SECRET_MISMATCH → KEY_REVOKED →
 * KEY_EXPIRED (inclusive: at expiresAt the key is already dead) →
 * KEY_OWNER_INACTIVE (suspension cascade). A broken codec throws
 * AUTH_HASH_PORT_INVALID.
 */
export function authenticateKey(
  existingKeys: readonly ApiKey[],
  args: AuthenticateKeyArgs,
  codec: SecretCodec,
  clock: Clock,
): AuthenticateKeyResult {
  assertSecretCodec(codec);
  const now = assertClockDate(clock.now(), 'AUTH_CLOCK_INVALID');
  const deny = (reason: KeyDenyReason, detail: string, key: ApiKey | null): AuthenticateKeyResult => ({
    authenticated: false,
    code: reason,
    reason,
    detail,
    event: authEvent(
      'auth.accessDenied',
      key === null ? args.orgId : key.keyId,
      {
        orgId: args.orgId,
        principalId: key === null ? null : key.keyId,
        principalKind: 'apiKey',
        permission: AUTH_ATTEMPT_PERMISSION,
        resource: null,
        reason,
        detail,
        at: now.toISOString(),
      },
      clock,
    ),
  });

  if (typeof args.secret !== 'string' || args.secret.length < KEY_PREFIX_LENGTH) {
    return deny('KEY_UNKNOWN', 'presented secret is shorter than a key prefix', null);
  }
  const prefix = args.secret.slice(0, KEY_PREFIX_LENGTH);
  const candidates = existingKeys.filter((k) => k.prefix === prefix);
  if (candidates.length === 0) {
    return deny('KEY_UNKNOWN', `no api key carries prefix '${prefix}'`, null);
  }
  const matched = candidates.find((k) => codec.verify(args.secret, k.secretHash));
  if (!matched) {
    return deny(
      'KEY_SECRET_MISMATCH',
      `secret does not match any key with prefix '${prefix}'`,
      candidates[0] ?? null,
    );
  }
  if (matched.status === 'revoked') {
    return deny(
      'KEY_REVOKED',
      `api key ${matched.keyId} was revoked at ${matched.revokedAt?.toISOString() ?? 'unknown'} — replay is denied and audited`,
      matched,
    );
  }
  if (matched.expiresAt !== null && now.getTime() >= matched.expiresAt.getTime()) {
    return deny(
      'KEY_EXPIRED',
      `api key ${matched.keyId} expired at ${matched.expiresAt.toISOString()}`,
      matched,
    );
  }
  if (args.ownerStatus !== undefined && args.ownerStatus !== null && args.ownerStatus !== 'active') {
    return deny(
      'KEY_OWNER_INACTIVE',
      `api key ${matched.keyId} owner is ${args.ownerStatus} — suspension cascades to the owner's keys`,
      matched,
    );
  }
  return {
    authenticated: true,
    key: { ...matched, lastUsedAt: now },
    event: null,
  };
}
